repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        files: \.(js|ts|json)$

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint
        language: node
        files: \.(js|ts)$
        additional_dependencies:
          - eslint
          - typescript
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
